using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InputManager : MonoBehaviour
{

    // this is our singleton
    public static InputManager instance;

    // a reference to the autogenerated control scheme
    Controls controls;

    // control data
    public Vector2 move;
    public bool jumpPressed;

    void Awake()
    {
        if(instance == null)
        {
            // if instance is null, we must set it to this
            instance = this;
        } else
        {
            // if it is not null, destroy this
            Destroy(this);
        }

        controls = new Controls();
        
    }

    private void OnEnable()
    {
        controls.Enable();
    }

    // Start is called before the first frame update
    void Start()
    {
        // *params* => code to execute
        controls.Locomotion.Move.performed += obj => move = obj.ReadValue<Vector2>();

        //listen for press on jump key
        controls.Locomotion.Jump.performed += obj => jumpPressed = true;
        controls.Locomotion.Jump.canceled += obj => jumpPressed = false;

    }

    void OnDisable()
    {
        controls.Disable();
    }

}
